version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: intern_management_db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: intern_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: intern_management_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/intern_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
